#!/usr/bin/env bash
# vim: noexpandtab ts=4 sw=4 ft=sh:

set -e
set +x

declare -r PAIR_SEPARATOR=+

function gp_my_name()
{
	GLOBAL_AUTHOR_NAME=$(git config --global user.name)
	LOCAL_AUTHOR_NAME=$(git config --local user.name)

	[[ -z "$GLOBAL_AUTHOR_NAME" ]] && { exit 0; }
	[[ "$LOCAL_AUTHOR_NAME" = "$GLOBAL_AUTHOR_NAME" ]] && { echo $LOCAL_AUTHOR_NAME; exit 0; }

	echo $GLOBAL_AUTHOR_NAME;
}

function gp_my_email()
{
	AUTHOR_EMAIL=$(git config user.email)

	echo $AUTHOR_EMAIL
}

function gp_add_author()
{
	PAIR_NAME=$1
	[[ -z "$1" ]] && { echo "Pair name is required, like 'John Doe'."; exit 100; }

	CURRENT_AUTHORS=$(git config user.name)
	[[ $( echo $CURRENT_AUTHORS | grep -e "$PAIR_NAME" ) != "" ]] && { echo "Author '$PAIR_NAME' already in list!"; exit 102;  }

	ORDERED_PAIR_NAMES_ONELINE=$(
		echo "${CURRENT_AUTHORS} ${PAIR_SEPARATOR} ${PAIR_NAME}" |
		tr ${PAIR_SEPARATOR} '\n' |
		sed 's/^ //g' |
		sed 's/ $//g' |
		sort |
		tr '\n' ${PAIR_SEPARATOR} |
		sed "s/${PAIR_SEPARATOR}$//g" | 
		sed "s/${PAIR_SEPARATOR}/ ${PAIR_SEPARATOR} /g"
	)


	git config --local user.name "$ORDERED_PAIR_NAMES_ONELINE"
	echo "Local authors name now are:" $(git config --local user.name)
}

function gp_reset_author()
{
	MY_NAME=$(gp_my_name)

	[[ -z "$MY_NAME" ]] && { echo "No global Git user, use 'git config --global user.name <your name>'."; exit 101; }

	git config --local user.name "$MY_NAME"
	echo "Local author name now is:" $(git config --local user.name)
}

if [ -z "$1" ]; then
	cat 1>&2 <<-CAT
	Usage: git pair <author name>
	       git pair ended

	Arguments:
	  <author name>       Name of the author you want to pair with, like
	                       "John Doe" or "Bob Marley".
	  ended               Resets the author name to your original name,
	                       defined on your global Git configuration. You can
	                       also use "finished" as an alternative.

	Bugs on http://github.com/augustohp/git-pair/issues
CAT
	exit 1;
fi

case "$1" in
	"ended" | "finished" )
		gp_reset_author
		;;
	* )
		gp_add_author "$1"
		;;
esac

